<?php
    /*  MODULE ALERTS  */

    // ALERTS ABOUT AYPAGE ACCOUNT
    // ALERTS ABOUT AYPAGE GENERAL INFORMATION/WARNINGS
    // ALERTS ABOUT TIP OF THE DAY
    // ALERTS ABOUT PROFILE INFORMATION
    // ALERTS ABOUT MESSAGE DELIVERY STATUS

    // DISPLAYING A TOP BAR ALERT
    // DISPLAYING A MINIBAR ALERT
?>